### ISSUE TITLE
提示action.type为undefined的话，应该是缺少了什么？

### ISSUE THREAD

**Issue by 452MJ** [songxiaoliang/react-navigation-redux#1]
![image](https://user-images.githubusercontent.com/13673008/27985137-38fccae0-6418-11e7-8c71-c82de8bbe660.png)

**Comment by 452MJ** [comment]
不知道哪里出问题了，一步步按着来写- -

除了在reducer里面写过action.type，其他地方我也没写过额

**Comment by 452MJ** [comment]
写多了个括号()。。。。

**Comment by 452MJ** [comment]
兄弟文笔不错！很清晰

**Comment by songxiaoliang** [comment]
@452MJ 哈哈，多谢支持~

**Comment by 452MJ** [comment]
@songxiaoliang 我有个问题，就是action应该怎么写？我看你的代码基本都是结合网络请求来做的，我现在想通过一个+1-1的计数器来尝试使用Redux，一直报红

![image](https://user-images.githubusercontent.com/13673008/28063426-ac8ab66e-6663-11e7-850b-6b4131c5c87c.png)
![image](https://user-images.githubusercontent.com/13673008/28063443-b59ec22c-6663-11e7-8052-4f9231a96ad4.png)

**Comment by songxiaoliang** [comment]
@452MJ redux中action就是使用dispatch去分发一个用户行为，像你这个计数器，那么当点击加或者减的时候，就应该分别对应dispatch即可。例如，点击减少，那么此时肯定要调用dispatch去分发一个任务：dispatch( { type: 'decrease'  } )

**Comment by 452MJ** [comment]
@songxiaoliang 是的我就是这么想的，只是在action.js里面不知道 具体怎么写，我这样写感觉也没问题啊，但就是报错了，说要返回一个方法function。
![image](https://user-images.githubusercontent.com/13673008/28075671-ba8b3bbe-668e-11e7-8a71-553a9e51f60f.png)

**Comment by songxiaoliang** [comment]
@452MJ 你好像缺少了一个return，这样写试下：
return dispatch => { 
    return dispatch(testState(value));
 }，

**Comment by 452MJ** [comment]
@songxiaoliang 还是报错QAQ，兄弟有联系方式？我的qq在主页
